"""empty message

Revision ID: 077032ca34cb
Revises: fed241137c54
Create Date: 2024-12-16 15:29:56.948931

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "077032ca34cb"
down_revision = "fed241137c54"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("key_code", sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("key_code")

    # ### end Alembic commands ###
