"""Add creator_id to Community

Revision ID: 1e1059cf51a2
Revises: 8ee0680921d4
Create Date: 2024-11-25 12:21:19.410236

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1e1059cf51a2"
down_revision = "8ee0680921d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.add_column(sa.Column("creator_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, "user", ["creator_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("creator_id")

    # ### end Alembic commands ###
