"""Create communities

Revision ID: 4216f943e506
Revises: 001
Create Date: 2024-11-11 21:06:46.394519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4216f943e506'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook')
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('data_set_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'community', ['community_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('ds_download_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('ds_download_record_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'community', ['community_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('ds_view_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('ds_view_record_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'community', ['community_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_view_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ds_view_record_ibfk_2', 'user', ['user_id'], ['id'])
        batch_op.drop_column('community_id')

    with op.batch_alter_table('ds_download_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ds_download_record_ibfk_2', 'user', ['user_id'], ['id'])
        batch_op.drop_column('community_id')

    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('data_set_ibfk_2', 'user', ['user_id'], ['id'])
        batch_op.drop_column('community_id')

    op.create_table('webhook',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
