"""empty message

Revision ID: ee93f50143fb
Revises: 3b264b998fdf
Create Date: 2024-11-13 22:16:32.879073

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ee93f50143fb"
down_revision = "3b264b998fdf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data_set", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.drop_constraint("data_set_ibfk_2", type_="foreignkey")
        batch_op.create_foreign_key(None, "user", ["user_id"], ["id"])
        batch_op.drop_column("community_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data_set", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "community_id",
                mysql.INTEGER(display_width=11),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "data_set_ibfk_2", "community", ["community_id"], ["id"]
        )
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
